main_text = """<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n
<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n
p, li { white-space: pre-wrap; }\n
</style></head><body style=\" font-family:\'Ubuntu\'; font-size:12pt; font-weight:400; font-style:normal;\">\n
<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Добро пожаловать в CryptoMaster</span></p>\n
<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Узнайте больше о мире криптографии и криптоанализа с нашим приложением. Мы предоставляем вам мощные инструменты для анализа и расшифровки шифрованных сообщений.</p>\n
<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Основные функции приложения:</span></p>\n
<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\"\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Анализ шифров:</span> Исследуйте различные методы шифрования.</li>\n
<li style=\"\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Расшифровка сообщений:</span> Попробуйте расшифровать зашифрованные сообщения.</li>\n
<li style=\"\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Секретные коды:</span> Погрузитесь в историю создания секретных кодов и шифров и узнайте, как они использовались в разведке и дипломатии.</li>\n
<li style=\"\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Современные и классические шифры: </span>Работайте с различными типами шифров, включая <b>шифр Цезаря</b>, <b>шифр Атбаш</b> и многие другие.</li></ul>\n
<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Приложение CryptoMaster</span> предоставляет вам инструменты, чтобы исследовать мир криптографии и наслаждаться разгадыванием секретных сообщений. У вас есть шанс стать настоящим криптоаналитиком!</p>\n
<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n
<p dir=\'rtl\' style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Автор: @thisisobserver</span></p></body></html>"""

text_about_us = """<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n
<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n
p, li { white-space: pre-wrap; }\n
</style></head><body style=\" font-family:\'Ubuntu\'; font-size:12pt; font-weight:400; font-style:normal;\">\n
<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'monospace\'; font-size:14pt; font-weight:600;\">📢 О Нас</span></p>\n
<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'monospace\'; font-weight:600;\"><br /></p>\n
<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'monospace\'; font-weight:600;\">Добро пожаловать в наше приложение! Мы - команда энтузиастов, увлеченных миром криптографии.</span></p>\n
<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'monospace\'; font-weight:600;\"><br /></p>\n
<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'monospace\';  font-weight:600;\">🌐 Социальные Сети</span></p>\n
<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'monospace\'; font-weight:600;\">Вы можете следить за нами и общаться с нами через социальные сети:</span></p>\n
<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'monospace\'; font-weight:600;\"><br /></p>\n
<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'monospace\'; font-weight:600;\">🎥 YouTube: </span><a href=\"https://www.youtube.com/watch?v=dQw4w9WgXcQ\"><span style=\" font-weight:600; text-decoration: underline; color:#0000ff;\">https://www.youtube.com</span></a></p>\n
<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'monospace\'; font-weight:600;\">📝 GitHub: </span><a href=\"https://github.com/7KaZaX7\"><span style=\" font-weight:600; text-decoration: underline; color:#0000ff;\">https://github.com</span></a></p>\n
<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'monospace\'; font-weight:600;\"><br /></p>\n
<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'monospace\'; font-weight:600;\">📧 Связь</span></p>\n
<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'monospace\'; font-weight:600;\">Если у вас есть вопросы, предложения или комментарии, не стесняйтесь связаться с нами:</span></p>\n
<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'monospace\'; font-weight:600;\"><br /></p>\n
<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'monospace\'; font-weight:600;\">📩 Электронная почта: dashaerevanlogican@gmail.com(или используйте вкладку other/support)</span></p>\n
<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'monospace\'; font-weight:600;\"><br /></p>\n
<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'monospace\'; font-weight:600;\"><br /></p>\n
<p style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'monospace\'; font-weight:600;\">Спасибо, что выбрали нас! Мы ценим вашу поддержку и готовы взаимодействовать с вами через социальные сети и другие каналы связи.</span></p></body></html>"""

text_about_codings = """<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n
<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n
p, li { white-space: pre-wrap; }\n
</style></head><body style=\" font-family:\'Ubuntu\'; font-size:12pt; font-weight:400; font-style:normal;\">\n
<h2 style=\" margin-top:16px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; text-decoration: underline;\">1. ASCII (American Standard Code for Information Interchange)</span></h2>\n
<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">ASCII - это одна из наиболее распространенных кодировок, которая используется для представления текста и управляющих символов с использованием семи или восьми битов. В кодировке ASCII каждому символу соответствует числовое значение, которое затем представляется в виде байта (8 битов). Эта кодировка включает в себя символы латинского алфавита, цифры, знаки препинания и специальные управляющие символы. Например, буква &quot;A&quot; в кодировке ASCII представлена числом 65.</span></p>\n
<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">ASCII чрезвычайно важна в программировании и обмене данных между компьютерами, так как позволяет однозначно представить символы в виде чисел.</span></p>\n
<h2 style=\" margin-top:16px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; text-decoration: underline;\">2. Код Бэкона (Bacon\'s Cipher)</span></h2>\n
<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Код Бэкона, названный в честь английского философа Фрэнсиса Бэкона, является методом шифрования текста, который представляет символы с использованием последовательности символов &quot;A&quot; и &quot;B&quot;. Каждая буква алфавита ассоциируется с уникальной последовательностью &quot;A&quot; и &quot;B&quot;. Например, буква &quot;A&quot; может быть представлена как &quot;AAAAA&quot;, а буква &quot;B&quot; как &quot;AAAAB&quot;. Этот код применяется для скрытой передачи сообщений и шифрования текста, где символы заменяются на соответствующие последовательности &quot;A&quot; и &quot;B&quot;.</span></p>\n
<h2 style=\" margin-top:16px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; text-decoration: underline;\">3. Код Морзе (Morse Code)</span></h2>\n
<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Код Морзе - это система кодирования, которая использует комбинации длинных и коротких сигналов (обычно в виде звуковых или световых импульсов) для представления букв и цифр. Этот код был разработан Сэмюэлем Морзе и Альфредом Вейлендом в 1830-х годах и широко применяется в телеграфии и радиосвязи. Каждая буква и цифра имеет свой уникальный набор коротких и длинных сигналов. Например, &quot;A&quot; кодируется как &quot;.-&quot; (точка, тире), а &quot;0&quot; как &quot;-----&quot; (пять точек).</span></p>\n
<h2 style=\" margin-top:16px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; text-decoration: underline;\">4. Base64</span></h2>\n
<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Base64 - это метод кодирования, который используется для преобразования бинарных данных в текстовый формат. Эта кодировка использует 64 символа, включая буквы латинского алфавита (заглавные и строчные), цифры и символы &quot;+&quot;, &quot;/&quot;. Base64 полезна, когда необходимо встраивать бинарные данные, такие как изображения или файлы, в текстовые форматы, например, в электронные письма или URL. Пример кодирования Base64: строка &quot;Hello&quot; преобразуется в &quot;SGVsbG8=&quot;.</span></p></body></html>"""

text_about_ciphers = """<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n
<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n
p, li { white-space: pre-wrap; }\n
</style></head><body style=\" font-family:\'Ubuntu\'; font-size:12pt; font-weight:400; font-style:normal;\">\n
<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:x-large; font-weight:600; text-decoration: underline;\">1. Шифр Цезаря (Caesar Cipher)</span></p>\n
<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Шифр Цезаря - один из наиболее известных и простых методов шифрования. Он был назван в честь римского императора Юлия Цезаря, который, по преданию, использовал этот метод для секретной переписки. Шифр Цезаря основан на сдвиге символов в алфавите. Каждая буква в сообщении заменяется другой буквой, находящейся на определенное количество позиций в алфавите. Например, при сдвиге на 3 позиции, буква &quot;A&quot; станет &quot;D&quot;, &quot;B&quot; станет &quot;E&quot;, и так далее. Расшифровать сообщение можно, зная величину сдвига. Этот метод прост в реализации, но не обладает высокой степенью безопасности.</span></p>\n
<h2 style=\" margin-top:16px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:x-large; font-weight:600; text-decoration: underline;\">2. XOR (Исключающее ИЛИ) Шифр</span></h2>\n
<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">XOR - это битовая операция, которая может быть использована для шифрования данных. В этом методе каждый бит исходного текста (или ключа) &quot;смешивается&quot; с соответствующим битом ключа с использованием операции XOR. Если биты одинаковые, результат XOR равен 0; если биты разные, результат равен 1. Применение XOR к каждому биту сообщения обеспечивает высокую степень безопасности, особенно если ключ длинный и случайно сгенерирован. XOR шифрование часто используется в современной криптографии.</span></p>\n
<h2 style=\" margin-top:16px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:x-large; font-weight:600; text-decoration: underline;\">3. Шифр Атбаш (Atbash Cipher)</span></h2>\n
<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Шифр Атбаш - это алфавитный шифр, который основан на зеркальном отображении букв алфавита. В этом методе каждая буква заменяется ей противоположной в алфавите. Например, &quot;A&quot; заменяется &quot;Z&quot;, &quot;B&quot; заменяется &quot;Y&quot;, и так далее. Шифр Атбаш легко понимать и использовать, но, как и Цезарь, он не предоставляет высокой степени защиты.</span></p></body></html>"""

text_about_qrcodes = """<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n
<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n
p, li { white-space: pre-wrap; }\n
</style></head><body style=\" font-family:\'Ubuntu\'; font-size:12pt; font-weight:400; font-style:normal;\">\n
<h2 style=\" margin-top:16px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:x-large; font-weight:600; text-decoration: underline;\">Что такое QR-код?</span></h2>\n
<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">QR-код - это двухмерный штрихкод, состоящий из чередующихся четырех угловых квадратов и небольших квадратных модулей внутри. Особенностью QR-кода является его способность хранить большое количество информации, включая текст, URL-адреса, контактные данные, геолокацию и многое другое. QR-коды бывают разных размеров, и их емкость зависит от количества модулей.</span></p>\n
<h2 style=\" margin-top:16px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:x-large; font-weight:600; text-decoration: underline;\">Как работают QR-коды?</span></h2>\n
<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">QR-коды работают на основе кодирования информации в виде чередующихся светлых и темных модулей. Чтобы декодировать информацию, необходимо использовать QR-reader, который может быть встроен в смартфоны или планшеты. Сканер считывает модули и интерпретирует их как текст, URL или другой формат данных. QR-коды могут содержать корректирующие коды, что обеспечивает надежное считывание данных даже при наличии небольших повреждений.</span></p></body></html>"""
